import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
    mode: deep_merge_prepend
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-r4.1.yml
language: python
python:
  - '3.5'
jobs:
  include:
   - python: 3.5
     install: pip install -r ci/requirements.txt
     script: python -m unittest discover -v imgconverter -p test.py
   - python: 3.6
     install: pip install -r ci/requirements.txt
     script: python -m unittest discover -v imgconverter -p test.py
   - python: 3.7
     install: pip install -r ci/requirements.txt
     script: python -m unittest discover -v imgconverter -p test.py
   - stage: deploy
     python: 3.6
     env: DIST_DOM0=fc32
     script: ~/qubes-builder/scripts/travis-deploy
