sudo: required
dist: trusty
language: python
python:
  - '2.7'
install:
 - test -z "$TESTS_ONLY" || pip install -r ci/requirements.txt
 - test -n "$TESTS_ONLY" || git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
script:
 - test -z "$TESTS_ONLY" || python -m unittest discover -v imgconverter
 - test -n "$TESTS_ONLY" || ~/qubes-builder/scripts/travis-build
env:
 - DIST_DOM0=fc25 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=fc24 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=fc25 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=fc26 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=jessie USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1

jobs:
  include:
   - env: TESTS_ONLY=1
     python: 2.7
   - env: TESTS_ONLY=1
     python: 3.4
   - env: TESTS_ONLY=1
     python: 3.5
